sudo: true
language: node_js
cache:
  yarn: true
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
  - node_modules
node_js:
  - 8
compiler:
- gcc
- clang
env:
- CXX=g++-4.8
script: 
  - ./node_modules/.bin/testrpc-sc&
  - ./node_modules/.bin/truffle test
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang